apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: backend
type: Opaque
stringData:
  DB_NAME: postgres
  DB_USER: usersadmin
  DB_PASSWORD: Password123
  DB_HOST: users-db.cuwqobskzn7f.us-east-1.rds.amazonaws.com
  DB_PORT: "5432"
  SECRET_KEY: 'django-insecure-^qyd#4up6$tx$(3cvr0w#7pq+5clb!1(^0&beekkjod7p((j0-'
  DEBUG: "False"  # ← CAMBIAR A False en producción
  # Después de crear el LoadBalancer, actualizar con la URL real:
  ALLOWED_HOSTS: "*"
# ALLOWED_HOSTS: "127.0.0.1,localhost,10.100.72.37,users-api-service,users-api-service.backend,users-api-service.backend.svc.cluster.local,a47fc2cb1cc1c41a7ba61e0595e63edc-1604893455.us-east-1.elb.amazonaws.com,.elb.amazonaws.com,.execute-api.us-east-1.amazonaws.com"
  # 127.0.0.1,localhost,backend,users-api-service,users-api-service.backend.svc.cluster.local,*.elb.amazonaws.com,*.execute-api.us-east-1.amazonaws.com



