apiVersion: v1
kind: Service
metadata:
  name: users-api-service
  namespace: proyecto-final
spec:
  selector:
    app: users-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP